logman stop -n usbtrace
logman delete -n usbtrace
logman stop -ets usbhub3
logman stop -ets ucx01000
logman stop -ets usbxhci
logman stop -ets usbhub
logman stop -ets usbport
logman stop -ets usbccgp
logman stop -ets winusb
logman stop -ets pci
move /Y %SystemRoot%\Tracing\usbtrace_000001.etl %SystemRoot%\Tracing\usbtrace.etl